services:
  main-platform:
    image: maven:3.8.6-openjdk-11
    container_name: main-platform
    volumes:
      - .:/app
    working_dir: /app
    command: >
      mvn -q clean compile exec:java
      -Djava.awt.headless=true
      -Dexec.mainClass=jade.Boot
      -Dexec.args="-name P1 -local-host main-platform -host main-platform -port 1099"
    ports:
      - "1099:1099"
    networks:
      - jade-net

  remote-container:
    image: maven:3.8.6-openjdk-11
    container_name: remote-container
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - main-platform
    command: >
      sh -c "sleep 10 &&
      mvn -q exec:java
      -Djava.awt.headless=true
      -Dexec.mainClass=jade.Boot
      -Dexec.args='-container -host main-platform -port 1099 -agents R1:com.jade.agentes.RecepcionistaAgent;T1:com.jade.agentes.TriageAgent;A1:com.jade.agentes.DoctorAssignerAgent;D1:com.jade.agentes.DoctorAgent'"
    networks:
      - jade-net

networks:
  jade-net:
    driver: bridge