  services:
    main-platform:
      image: maven:3.8.6-openjdk-11
      volumes:
        - .:/app
      working_dir: /app
      command: mvn clean compile exec:java -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dexec.mainClass="jade.Boot" -Dexec.args="-name P1 -host main-platform -agents A1:com.jade.agentes.AgenteInicial;A3:com.jade.agentes.AgenteInicial"
      ports:
        - "1099:1099" # Puerto principal de JADE

    remote-container:
      image: maven:3.8.6-openjdk-11
      volumes:
        - .:/app
      working_dir: /app
      command: mvn exec:java -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dexec.mainClass="jade.Boot" -Dexec.args="-container -host main-platform -agents A2:com.jade.agentes.AgenteInicial;A4:com.jade.agentes.AgenteInicial"
      depends_on:
        - main-platform